baseURL = 'https://aliscott.github.io/cloudfrustration/'
languageCode = 'en-us'
title = 'CloudFrustration'
theme = 'frustration'

[params]
subtitle = "Documenting an engineer's descent into madness while adding CloudFormation support to Infracost"
